2019-03-17 19:06:25,941-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:26,031-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'mobilephone': '15871802607', 'pwd': '123456', 'regname': '自闭患者'}，结果是{'msg': '注册成功', 'data': None, 'code': '10001', 'status': 1}
2019-03-17 19:06:26,168-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:26,174-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:26,238-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'mobilephone': '13412345678', 'pwd': '12345', 'regname': '哎呀'}，结果是{'msg': '密码长度必须为6~18', 'data': None, 'code': '20108', 'status': 0}
2019-03-17 19:06:26,360-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:26,366-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:26,434-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'mobilephone': '13412345678', 'pwd': '1234567891234567891', 'regname': '妈呀'}，结果是{'msg': '密码长度必须为6~18', 'data': None, 'code': '20108', 'status': 0}
2019-03-17 19:06:26,544-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:26,550-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:26,616-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'mobilephone': 'abcd', 'pwd': '123456', 'regname': '小皮球'}，结果是{'msg': '手机号码格式不正确', 'data': None, 'code': '20109', 'status': 0}
2019-03-17 19:06:26,737-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:26,743-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:26,821-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'mobilephone': '13412345679', 'pwd': '123456', 'regname': '小晚晴'}，结果是{'msg': '手机号码已被注册', 'data': None, 'code': '20110', 'status': 0}
2019-03-17 19:06:26,937-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:26,943-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:27,017-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'mobilephone': '13512365669', 'pwd': '123456'}，结果是{'msg': '登录成功', 'data': None, 'code': '10001', 'status': 1}
2019-03-17 19:06:27,164-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:27,175-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:27,255-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'mobilephone': '1341234567', 'pwd': '123456'}，结果是{'msg': '用户名或密码错误', 'data': None, 'code': '20111', 'status': 0}
2019-03-17 19:06:27,402-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:27,411-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:27,481-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'mobilephone': '134123456789', 'pwd': '123456'}，结果是{'msg': '用户名或密码错误', 'data': None, 'code': '20111', 'status': 0}
2019-03-17 19:06:27,632-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:27,640-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:27,708-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'msg': '手机号不能为空', 'data': None, 'code': '20103', 'status': 0}
2019-03-17 19:06:27,826-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:27,833-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:27,894-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'msg': '密码不能为空', 'data': None, 'code': '20103', 'status': 0}
2019-03-17 19:06:28,006-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:28,012-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:28,099-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'msg': '充值成功', 'data': {'regtime': '2019-03-10 20:10:00.0', 'type': '1', 'id': 1123430, 'mobilephone': '13512365669', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'leaveamount': '3209856.00', 'regname': 'å°\x8få°\x8fé\x9bª'}, 'code': '10001', 'status': 1}
2019-03-17 19:06:28,211-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:28,218-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:28,280-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'msg': '手机号码格式不正确', 'data': None, 'code': '20109', 'status': 0}
2019-03-17 19:06:28,393-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:28,400-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:28,475-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117', 'status': 0}
2019-03-17 19:06:28,600-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:28,608-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:28,672-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117', 'status': 0}
2019-03-17 19:06:28,786-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:28,792-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:28,856-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'mobilephone': '13512365669', 'amount': '哈哈哈'}，结果是{'msg': '请输入数字', 'data': None, 'code': '20118', 'status': 0}
2019-03-17 19:06:28,989-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:28,996-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:29,116-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'msg': '取现成功', 'data': {'regtime': '2019-03-10 20:10:00.0', 'type': '1', 'id': 1123430, 'mobilephone': '13512365669', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'leaveamount': '3086400.00', 'regname': 'å°\x8få°\x8fé\x9bª'}, 'code': '10001', 'status': 1}
2019-03-17 19:06:29,238-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:29,245-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:29,305-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'msg': '手机号码格式不正确', 'data': None, 'code': '20109', 'status': 0}
2019-03-17 19:06:29,416-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:29,423-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:29,490-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117', 'status': 0}
2019-03-17 19:06:29,609-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:29,616-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:29,683-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117', 'status': 0}
2019-03-17 19:06:29,796-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:29,803-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:29,870-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'mobilephone': '13512365669', 'amount': '100.333333'}，结果是{'msg': '输入金额的金额小数不能超过两位', 'data': None, 'code': '20116', 'status': 0}
2019-03-17 19:06:29,993-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:29,999-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:30,066-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'memberId': '1', 'loanId': 1, 'password': '123456', 'amount': '1000'}，结果是{'msg': '不存在该用户', 'data': None, 'code': '11008', 'status': 0}
2019-03-17 19:06:30,192-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:30,200-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:30,266-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'memberId': '1', 'loanId': 1, 'password': '100.333333', 'amount': '1020'}，结果是{'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None, 'code': '11007', 'status': 0}
2019-03-17 19:06:30,379-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:30,386-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:30,456-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'memberId': '01010', 'loanId': 1, 'password': '100.333333', 'amount': '1020'}，结果是{'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None, 'code': '11007', 'status': 0}
2019-03-17 19:06:30,571-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:30,578-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:30,638-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'msg': '参数错误:所有参数都不能为空', 'data': None, 'code': '11003', 'status': 0}
2019-03-17 19:06:30,752-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:30,759-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:30,820-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'memberId': '01010', 'loanId': '0.2', 'password': '100.333333', 'amount': '1020'}，结果是{'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None, 'code': '11007', 'status': 0}
2019-03-17 19:06:30,938-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:30,945-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:31,010-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:31,021-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:31,085-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:31,093-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:31,162-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:31,170-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:31,233-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:31,242-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:31,308-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:56,311-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:56,383-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'regname': '自闭患者', 'mobilephone': '15871802608', 'pwd': '123456'}，结果是{'status': 1, 'msg': '注册成功', 'code': '10001', 'data': None}
2019-03-17 19:06:56,493-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:56,499-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:56,567-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'regname': '哎呀', 'mobilephone': '13412345678', 'pwd': '12345'}，结果是{'status': 0, 'msg': '密码长度必须为6~18', 'code': '20108', 'data': None}
2019-03-17 19:06:56,677-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:56,683-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:56,744-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'regname': '妈呀', 'mobilephone': '13412345678', 'pwd': '1234567891234567891'}，结果是{'status': 0, 'msg': '密码长度必须为6~18', 'code': '20108', 'data': None}
2019-03-17 19:06:56,852-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:56,858-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:56,930-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'regname': '小皮球', 'mobilephone': 'abcd', 'pwd': '123456'}，结果是{'status': 0, 'msg': '手机号码格式不正确', 'code': '20109', 'data': None}
2019-03-17 19:06:57,044-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:57,050-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:57,121-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'regname': '小晚晴', 'mobilephone': '13412345679', 'pwd': '123456'}，结果是{'status': 0, 'msg': '手机号码已被注册', 'code': '20110', 'data': None}
2019-03-17 19:06:57,247-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:57,253-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:57,327-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'mobilephone': '13512365669', 'pwd': '123456'}，结果是{'status': 1, 'msg': '登录成功', 'code': '10001', 'data': None}
2019-03-17 19:06:57,443-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:57,449-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:57,518-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'mobilephone': '1341234567', 'pwd': '123456'}，结果是{'status': 0, 'msg': '用户名或密码错误', 'code': '20111', 'data': None}
2019-03-17 19:06:57,642-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:57,649-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:57,715-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'mobilephone': '134123456789', 'pwd': '123456'}，结果是{'status': 0, 'msg': '用户名或密码错误', 'code': '20111', 'data': None}
2019-03-17 19:06:57,834-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:57,840-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:57,901-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'status': 0, 'msg': '手机号不能为空', 'code': '20103', 'data': None}
2019-03-17 19:06:58,062-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:58,068-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:58,132-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'status': 0, 'msg': '密码不能为空', 'code': '20103', 'data': None}
2019-03-17 19:06:58,257-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:58,264-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:58,344-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'msg': '充值成功', 'code': '10001', 'data': {'leaveamount': '3209856.00', 'type': '1', 'id': 1123430, 'regtime': '2019-03-10 20:10:00.0', 'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E'}}
2019-03-17 19:06:58,459-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:58,465-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:58,546-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'msg': '手机号码格式不正确', 'code': '20109', 'data': None}
2019-03-17 19:06:58,663-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:58,670-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:58,751-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'code': '20117', 'data': None}
2019-03-17 19:06:58,862-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:58,869-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:58,934-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'code': '20117', 'data': None}
2019-03-17 19:06:59,054-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:59,063-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:59,130-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'amount': '哈哈哈', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入数字', 'code': '20118', 'data': None}
2019-03-17 19:06:59,273-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:59,279-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:59,359-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'msg': '取现成功', 'code': '10001', 'data': {'leaveamount': '3086400.00', 'type': '1', 'id': 1123430, 'regtime': '2019-03-10 20:10:00.0', 'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E'}}
2019-03-17 19:06:59,480-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:59,489-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:59,552-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'msg': '手机号码格式不正确', 'code': '20109', 'data': None}
2019-03-17 19:06:59,660-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:59,666-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:59,761-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'code': '20117', 'data': None}
2019-03-17 19:06:59,873-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:06:59,879-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:06:59,946-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'code': '20117', 'data': None}
2019-03-17 19:07:00,081-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:00,088-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:00,151-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'amount': '100.333333', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '输入金额的金额小数不能超过两位', 'code': '20116', 'data': None}
2019-03-17 19:07:00,263-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:00,270-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:00,333-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'password': '123456', 'memberId': '1', 'amount': '1000', 'loanId': 1}，结果是{'status': 0, 'msg': '不存在该用户', 'code': '11008', 'data': None}
2019-03-17 19:07:00,446-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:00,452-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:00,511-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'password': '100.333333', 'memberId': '1', 'amount': '1020', 'loanId': 1}，结果是{'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'code': '11007', 'data': None}
2019-03-17 19:07:00,622-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:00,628-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:00,690-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'password': '100.333333', 'memberId': '01010', 'amount': '1020', 'loanId': 1}，结果是{'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'code': '11007', 'data': None}
2019-03-17 19:07:00,802-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:00,808-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:00,874-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'status': 0, 'msg': '参数错误:所有参数都不能为空', 'code': '11003', 'data': None}
2019-03-17 19:07:00,995-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:01,001-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:01,062-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'password': '100.333333', 'memberId': '01010', 'amount': '1020', 'loanId': '0.2'}，结果是{'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'code': '11007', 'data': None}
2019-03-17 19:07:01,186-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:01,192-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:01,253-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:01,263-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:01,331-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:01,338-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:01,399-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:01,408-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:01,483-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-17 19:07:01,491-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-17 19:07:01,556-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:33,245-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:33,603-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'mobilephone': '15871802609', 'regname': '自闭患者', 'pwd': '123456'}，结果是{'status': 1, 'data': None, 'code': '10001', 'msg': '注册成功'}
2019-03-19 22:22:33,719-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:33,726-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:33,812-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'mobilephone': '13412345678', 'regname': '哎呀', 'pwd': '12345'}，结果是{'status': 0, 'data': None, 'code': '20108', 'msg': '密码长度必须为6~18'}
2019-03-19 22:22:33,952-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:33,959-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:34,077-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'mobilephone': '13412345678', 'regname': '妈呀', 'pwd': '1234567891234567891'}，结果是{'status': 0, 'data': None, 'code': '20108', 'msg': '密码长度必须为6~18'}
2019-03-19 22:22:34,207-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:34,213-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:34,335-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'mobilephone': 'abcd', 'regname': '小皮球', 'pwd': '123456'}，结果是{'status': 0, 'data': None, 'code': '20109', 'msg': '手机号码格式不正确'}
2019-03-19 22:22:34,490-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:34,497-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:34,593-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'mobilephone': '13412345679', 'regname': '小晚晴', 'pwd': '123456'}，结果是{'status': 0, 'data': None, 'code': '20110', 'msg': '手机号码已被注册'}
2019-03-19 22:22:34,754-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:34,767-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:34,903-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'mobilephone': '13512365669', 'pwd': '123456'}，结果是{'status': 1, 'data': None, 'code': '10001', 'msg': '登录成功'}
2019-03-19 22:22:35,089-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:35,099-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:35,209-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'mobilephone': '1341234567', 'pwd': '123456'}，结果是{'status': 0, 'data': None, 'code': '20111', 'msg': '用户名或密码错误'}
2019-03-19 22:22:35,337-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:35,344-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:35,430-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'mobilephone': '134123456789', 'pwd': '123456'}，结果是{'status': 0, 'data': None, 'code': '20111', 'msg': '用户名或密码错误'}
2019-03-19 22:22:35,585-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:35,593-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:35,750-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'status': 0, 'data': None, 'code': '20103', 'msg': '手机号不能为空'}
2019-03-19 22:22:35,892-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:35,900-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:35,995-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'status': 0, 'data': None, 'code': '20103', 'msg': '密码不能为空'}
2019-03-19 22:22:36,145-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:36,152-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:36,244-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'status': 1, 'data': {'mobilephone': '13512365669', 'type': '1', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'leaveamount': '3209856.00', 'id': 1123430, 'regname': 'å°\x8få°\x8fé\x9bª', 'regtime': '2019-03-10 20:10:00.0'}, 'code': '10001', 'msg': '充值成功'}
2019-03-19 22:22:36,359-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:36,367-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:36,451-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'status': 0, 'data': None, 'code': '20109', 'msg': '手机号码格式不正确'}
2019-03-19 22:22:36,568-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:36,574-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:36,648-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'status': 0, 'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-19 22:22:36,763-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:36,770-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:36,867-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'status': 0, 'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-19 22:22:36,985-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:36,994-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:37,066-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'mobilephone': '13512365669', 'amount': '哈哈哈'}，结果是{'status': 0, 'data': None, 'code': '20118', 'msg': '请输入数字'}
2019-03-19 22:22:37,204-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:37,222-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:37,362-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'status': 1, 'data': {'mobilephone': '13512365669', 'type': '1', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'leaveamount': '3086400.00', 'id': 1123430, 'regname': 'å°\x8få°\x8fé\x9bª', 'regtime': '2019-03-10 20:10:00.0'}, 'code': '10001', 'msg': '取现成功'}
2019-03-19 22:22:37,510-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:37,520-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:37,619-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'status': 0, 'data': None, 'code': '20109', 'msg': '手机号码格式不正确'}
2019-03-19 22:22:37,742-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:37,751-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:37,831-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'status': 0, 'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-19 22:22:37,986-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:37,994-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:38,130-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'status': 0, 'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-19 22:22:38,273-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:38,280-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:38,455-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'mobilephone': '13512365669', 'amount': '100.333333'}，结果是{'status': 0, 'data': None, 'code': '20116', 'msg': '输入金额的金额小数不能超过两位'}
2019-03-19 22:22:38,601-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:38,608-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:38,699-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'loanId': 1, 'password': '123456', 'memberId': '1', 'amount': '1000'}，结果是{'status': 0, 'data': None, 'code': '11008', 'msg': '不存在该用户'}
2019-03-19 22:22:38,848-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:38,855-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:38,975-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'loanId': 1, 'password': '100.333333', 'memberId': '1', 'amount': '1020'}，结果是{'status': 0, 'data': None, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数'}
2019-03-19 22:22:39,093-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:39,100-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:39,197-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'loanId': 1, 'password': '100.333333', 'memberId': '01010', 'amount': '1020'}，结果是{'status': 0, 'data': None, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数'}
2019-03-19 22:22:39,330-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:39,337-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:39,407-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'status': 0, 'data': None, 'code': '11003', 'msg': '参数错误:所有参数都不能为空'}
2019-03-19 22:22:39,554-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:39,561-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:39,634-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'loanId': '0.2', 'password': '100.333333', 'memberId': '01010', 'amount': '1020'}，结果是{'status': 0, 'data': None, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数'}
2019-03-19 22:22:39,769-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:39,778-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:39,857-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:39,915-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:39,987-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:39,999-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:40,095-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:40,126-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:40,208-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:22:40,232-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:22:40,308-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:23,635-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:23,731-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'mobilephone': '15871802610', 'regname': '自闭患者', 'pwd': '123456'}，结果是{'data': None, 'code': '10001', 'status': 1, 'msg': '注册成功'}
2019-03-19 22:25:23,853-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:23,859-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:23,925-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'mobilephone': '13412345678', 'regname': '哎呀', 'pwd': '12345'}，结果是{'data': None, 'code': '20108', 'status': 0, 'msg': '密码长度必须为6~18'}
2019-03-19 22:25:24,048-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:24,055-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:24,165-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'mobilephone': '13412345678', 'regname': '妈呀', 'pwd': '1234567891234567891'}，结果是{'data': None, 'code': '20108', 'status': 0, 'msg': '密码长度必须为6~18'}
2019-03-19 22:25:24,299-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:24,306-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:24,573-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'mobilephone': 'abcd', 'regname': '小皮球', 'pwd': '123456'}，结果是{'data': None, 'code': '20109', 'status': 0, 'msg': '手机号码格式不正确'}
2019-03-19 22:25:24,694-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:24,701-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:24,767-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'mobilephone': '13412345679', 'regname': '小晚晴', 'pwd': '123456'}，结果是{'data': None, 'code': '20110', 'status': 0, 'msg': '手机号码已被注册'}
2019-03-19 22:25:24,891-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:24,898-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:24,998-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'mobilephone': '13512365669', 'pwd': '123456'}，结果是{'data': None, 'code': '10001', 'status': 1, 'msg': '登录成功'}
2019-03-19 22:25:25,116-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:25,125-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:25,262-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'mobilephone': '1341234567', 'pwd': '123456'}，结果是{'data': None, 'code': '20111', 'status': 0, 'msg': '用户名或密码错误'}
2019-03-19 22:25:25,390-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:25,398-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:25,517-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'mobilephone': '134123456789', 'pwd': '123456'}，结果是{'data': None, 'code': '20111', 'status': 0, 'msg': '用户名或密码错误'}
2019-03-19 22:25:25,684-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:25,691-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:25,815-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'data': None, 'code': '20103', 'status': 0, 'msg': '手机号不能为空'}
2019-03-19 22:25:25,948-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:25,955-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:26,065-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'data': None, 'code': '20103', 'status': 0, 'msg': '密码不能为空'}
2019-03-19 22:25:26,202-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:26,208-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:26,323-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'data': {'mobilephone': '13512365669', 'leaveamount': '3209856.00', 'regtime': '2019-03-10 20:10:00.0', 'regname': 'å°\x8få°\x8fé\x9bª', 'type': '1', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430}, 'code': '10001', 'status': 1, 'msg': '充值成功'}
2019-03-19 22:25:26,452-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:26,458-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:26,521-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'data': None, 'code': '20109', 'status': 0, 'msg': '手机号码格式不正确'}
2019-03-19 22:25:26,649-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:26,656-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:26,764-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'data': None, 'code': '20117', 'status': 0, 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-19 22:25:26,907-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:26,915-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:26,985-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'data': None, 'code': '20117', 'status': 0, 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-19 22:25:27,116-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:27,125-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:27,238-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'mobilephone': '13512365669', 'amount': '哈哈哈'}，结果是{'data': None, 'code': '20118', 'status': 0, 'msg': '请输入数字'}
2019-03-19 22:25:27,383-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:27,390-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:27,477-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'data': {'mobilephone': '13512365669', 'leaveamount': '3086400.00', 'regtime': '2019-03-10 20:10:00.0', 'regname': 'å°\x8få°\x8fé\x9bª', 'type': '1', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430}, 'code': '10001', 'status': 1, 'msg': '取现成功'}
2019-03-19 22:25:27,607-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:27,620-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:27,764-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'data': None, 'code': '20109', 'status': 0, 'msg': '手机号码格式不正确'}
2019-03-19 22:25:27,897-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:27,904-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:28,021-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'data': None, 'code': '20117', 'status': 0, 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-19 22:25:28,151-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:28,158-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:28,248-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'data': None, 'code': '20117', 'status': 0, 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-19 22:25:28,363-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:28,371-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:28,556-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'mobilephone': '13512365669', 'amount': '100.333333'}，结果是{'data': None, 'code': '20116', 'status': 0, 'msg': '输入金额的金额小数不能超过两位'}
2019-03-19 22:25:28,676-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:28,684-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:28,793-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'memberId': '1', 'password': '123456', 'loanId': 1, 'amount': '1000'}，结果是{'data': None, 'code': '11008', 'status': 0, 'msg': '不存在该用户'}
2019-03-19 22:25:28,921-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:28,929-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:29,018-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'memberId': '1', 'password': '100.333333', 'loanId': 1, 'amount': '1020'}，结果是{'data': None, 'code': '11007', 'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数'}
2019-03-19 22:25:29,141-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:29,151-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:29,258-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'memberId': '01010', 'password': '100.333333', 'loanId': 1, 'amount': '1020'}，结果是{'data': None, 'code': '11007', 'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数'}
2019-03-19 22:25:29,419-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:29,427-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:29,545-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'data': None, 'code': '11003', 'status': 0, 'msg': '参数错误:所有参数都不能为空'}
2019-03-19 22:25:29,662-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:29,669-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:29,774-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'memberId': '01010', 'password': '100.333333', 'loanId': '0.2', 'amount': '1020'}，结果是{'data': None, 'code': '11007', 'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数'}
2019-03-19 22:25:29,902-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:29,908-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:29,998-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:30,009-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:30,102-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:30,119-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:30,203-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:30,212-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:30,322-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:25:30,345-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:25:30,408-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:38,614-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:38,843-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:38,851-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:39,041-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:39,048-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:39,262-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:39,269-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:39,472-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:39,481-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:39,683-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:39,690-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:39,951-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:39,958-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:40,127-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:40,134-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:40,332-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:40,339-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:40,577-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:40,584-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:40,854-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:40,862-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:41,083-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:41,090-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:41,309-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:41,316-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:41,557-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:41,565-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:41,818-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:41,825-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:42,147-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:42,154-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:42,487-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:42,493-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:42,892-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:42,899-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:43,127-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:43,134-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:43,321-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:43,328-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:43,539-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:43,547-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:43,769-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:43,783-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:43,960-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:43,971-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:44,173-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:44,180-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:44,381-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:44,388-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:44,559-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:44,566-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:44,670-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是Expecting value: line 1 column 1 (char 0)
2019-03-19 22:26:44,803-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:44,812-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:44,890-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是name 'null' is not defined
2019-03-19 22:26:45,035-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:45,042-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:45,151-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是name 'null' is not defined
2019-03-19 22:26:45,279-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:45,287-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:45,376-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是name 'null' is not defined
2019-03-19 22:26:45,513-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:26:45,520-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:26:45,630-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是name 'null' is not defined
2019-03-19 22:26:45,758-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:55,258-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:55,354-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'pwd': '123456', 'regname': '自闭患者', 'mobilephone': '15871802612'}，结果是{'code': '10001', 'status': 1, 'msg': '注册成功', 'data': None}
2019-03-19 22:28:55,361-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '注册成功', 'code': '10001', 'status': 1} != '{"status":1,"code":"10001","data":null,"msg":"注册成功"}'
2019-03-19 22:28:55,482-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:55,490-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:55,620-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'pwd': '12345', 'regname': '哎呀', 'mobilephone': '13412345678'}，结果是{'code': '20108', 'status': 0, 'msg': '密码长度必须为6~18', 'data': None}
2019-03-19 22:28:55,629-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '密码长度必须为6~18', 'code': '20108', 'status': 0} != '{"status":0,"code":"20108","data":null,"msg":"密码长度必须为6~18"}'
2019-03-19 22:28:55,751-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:55,759-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:55,858-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'pwd': '1234567891234567891', 'regname': '妈呀', 'mobilephone': '13412345678'}，结果是{'code': '20108', 'status': 0, 'msg': '密码长度必须为6~18', 'data': None}
2019-03-19 22:28:55,866-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '密码长度必须为6~18', 'code': '20108', 'status': 0} != '{"status":0,"code":"20108","data":null,"msg":"密码长度必须为6~18"}'
2019-03-19 22:28:55,983-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:55,991-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:56,083-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'pwd': '123456', 'regname': '小皮球', 'mobilephone': 'abcd'}，结果是{'code': '20109', 'status': 0, 'msg': '手机号码格式不正确', 'data': None}
2019-03-19 22:28:56,092-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '手机号码格式不正确', 'code': '20109', 'status': 0} != '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}'
2019-03-19 22:28:56,213-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:56,221-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:56,340-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'pwd': '123456', 'regname': '小晚晴', 'mobilephone': '13412345679'}，结果是{'code': '20110', 'status': 0, 'msg': '手机号码已被注册', 'data': None}
2019-03-19 22:28:56,354-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '手机号码已被注册', 'code': '20110', 'status': 0} != '{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}'
2019-03-19 22:28:56,471-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:56,478-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:56,604-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'pwd': '123456', 'mobilephone': '13512365669'}，结果是{'code': '10001', 'status': 1, 'msg': '登录成功', 'data': None}
2019-03-19 22:28:56,614-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '登录成功', 'code': '10001', 'status': 1} != '{"status":1,"code":"10001","data":null,"msg":"登录成功"}'
2019-03-19 22:28:56,737-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:56,744-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:56,852-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'pwd': '123456', 'mobilephone': '1341234567'}，结果是{'code': '20111', 'status': 0, 'msg': '用户名或密码错误', 'data': None}
2019-03-19 22:28:56,869-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '用户名或密码错误', 'code': '20111', 'status': 0} != '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}'
2019-03-19 22:28:56,987-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:56,994-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:57,175-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'pwd': '123456', 'mobilephone': '134123456789'}，结果是{'code': '20111', 'status': 0, 'msg': '用户名或密码错误', 'data': None}
2019-03-19 22:28:57,193-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '用户名或密码错误', 'code': '20111', 'status': 0} != '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}'
2019-03-19 22:28:57,312-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:57,320-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:57,437-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'code': '20103', 'status': 0, 'msg': '手机号不能为空', 'data': None}
2019-03-19 22:28:57,452-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '手机号不能为空', 'code': '20103', 'status': 0} != '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}'
2019-03-19 22:28:57,573-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:57,581-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:57,665-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'code': '20103', 'status': 0, 'msg': '密码不能为空', 'data': None}
2019-03-19 22:28:57,672-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '密码不能为空', 'code': '20103', 'status': 0} != '{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}'
2019-03-19 22:28:57,795-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:57,807-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:59,009-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'code': '10001', 'status': 1, 'msg': '充值成功', 'data': {'regtime': '2019-03-10 20:10:00.0', 'type': '1', 'regname': 'å°\x8få°\x8fé\x9bª', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430, 'leaveamount': '3209856.00', 'mobilephone': '13512365669'}}
2019-03-19 22:28:59,031-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '10001', 'status': 1, 'msg': '充值[208 chars]69'}} != '{"status":1,"code":"10001","data":{"id":[190 chars]成功"}'
2019-03-19 22:28:59,159-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:59,169-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:59,258-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'code': '20109', 'status': 0, 'msg': '手机号码格式不正确', 'data': None}
2019-03-19 22:28:59,265-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': None, 'msg': '手机号码格式不正确', 'code': '20109', 'status': 0} != '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}'
2019-03-19 22:28:59,402-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:59,410-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:59,491-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'code': '20117', 'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-19 22:28:59,498-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'status': 0} != '{"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}'
2019-03-19 22:28:59,660-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:59,670-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:28:59,790-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'code': '20117', 'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-19 22:28:59,800-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'status': 0} != '{"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}'
2019-03-19 22:28:59,940-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:28:59,949-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:00,031-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'amount': '哈哈哈', 'mobilephone': '13512365669'}，结果是{'code': '20118', 'status': 0, 'msg': '请输入数字', 'data': None}
2019-03-19 22:29:00,039-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '20118', 'msg': '请输入数字', 'data': None, 'status': 0} != '{"status":0,"code":"20118","data":null,"msg":"请输入数字"}'
2019-03-19 22:29:00,210-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:00,222-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:00,338-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'code': '10001', 'status': 1, 'msg': '取现成功', 'data': {'regtime': '2019-03-10 20:10:00.0', 'type': '1', 'regname': 'å°\x8få°\x8fé\x9bª', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430, 'leaveamount': '3086400.00', 'mobilephone': '13512365669'}}
2019-03-19 22:29:00,347-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': {'regtime': '2019-03-10 20:10:00[208 chars]001'} != '{"status":1,"code":"10001","data":{"id":[190 chars]成功"}'
2019-03-19 22:29:00,514-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:00,526-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:00,637-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'code': '20109', 'status': 0, 'msg': '手机号码格式不正确', 'data': None}
2019-03-19 22:29:00,646-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '20109', 'msg': '手机号码格式不正确', 'data': None, 'status': 0} != '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}'
2019-03-19 22:29:00,801-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:00,809-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:00,894-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'code': '20117', 'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-19 22:29:00,903-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'status': 0} != '{"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}'
2019-03-19 22:29:01,059-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:01,070-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:01,196-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'code': '20117', 'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-19 22:29:01,204-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'status': 0} != '{"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}'
2019-03-19 22:29:01,348-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:01,356-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:01,464-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'amount': '100.333333', 'mobilephone': '13512365669'}，结果是{'code': '20116', 'status': 0, 'msg': '输入金额的金额小数不能超过两位', 'data': None}
2019-03-19 22:29:01,473-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '20116', 'msg': '输入金额的金额小数不能超过两位', 'data': None, 'status': 0} != '{"status":0,"code":"20116","data":null,"msg":"输入金额的金额小数不能超过两位"}'
2019-03-19 22:29:01,621-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:01,631-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:01,906-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'password': '123456', 'memberId': '1', 'loanId': 1, 'amount': '1000'}，结果是{'code': '11008', 'status': 0, 'msg': '不存在该用户', 'data': None}
2019-03-19 22:29:01,913-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '11008', 'msg': '不存在该用户', 'data': None, 'status': 0} != '{"status":0,"code":"11008","data":null,"msg":"不存在该用户"}'
2019-03-19 22:29:02,051-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:02,059-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:02,157-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'password': '100.333333', 'memberId': '1', 'loanId': 1, 'amount': '1020'}，结果是{'code': '11007', 'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None}
2019-03-19 22:29:02,164-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None, 'status': 0} != '{"status":0,"code":"11007","data":null,"msg":"参数错误，投资金额必须是能被100整除的正整数"}'
2019-03-19 22:29:02,317-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:02,327-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:02,417-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'password': '100.333333', 'memberId': '01010', 'loanId': 1, 'amount': '1020'}，结果是{'code': '11007', 'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None}
2019-03-19 22:29:02,427-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None, 'status': 0} != '{"status":0,"code":"11007","data":null,"msg":"参数错误，投资金额必须是能被100整除的正整数"}'
2019-03-19 22:29:02,602-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:02,612-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:02,693-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'code': '11003', 'status': 0, 'msg': '参数错误:所有参数都不能为空', 'data': None}
2019-03-19 22:29:02,701-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '11003', 'msg': '参数错误:所有参数都不能为空', 'data': None, 'status': 0} != '{"status":0,"code":"11003","data":null,"msg":"参数错误:所有参数都不能为空"}'
2019-03-19 22:29:02,856-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:02,870-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:03,018-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'password': '100.333333', 'memberId': '01010', 'loanId': '0.2', 'amount': '1020'}，结果是{'code': '11007', 'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None}
2019-03-19 22:29:03,025-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None, 'status': 0} != '{"status":0,"code":"11007","data":null,"msg":"参数错误，投资金额必须是能被100整除的正整数"}'
2019-03-19 22:29:03,192-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:03,203-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:03,296-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:03,308-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:03,401-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:03,413-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:03,517-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:03,526-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:03,608-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-19 22:29:03,619-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-19 22:29:03,749-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:15,081-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:15,357-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'pwd': '123456', 'mobilephone': '15871802615', 'regname': '自闭患者'}，结果是{'status': 1, 'data': None, 'code': '10001', 'msg': '注册成功'}
2019-03-21 22:21:15,459-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:15,466-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:15,527-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'pwd': '12345', 'mobilephone': '13412345678', 'regname': '哎呀'}，结果是{'status': 0, 'data': None, 'code': '20108', 'msg': '密码长度必须为6~18'}
2019-03-21 22:21:15,642-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:15,649-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:15,739-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'pwd': '1234567891234567891', 'mobilephone': '13412345678', 'regname': '妈呀'}，结果是{'status': 0, 'data': None, 'code': '20108', 'msg': '密码长度必须为6~18'}
2019-03-21 22:21:15,842-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:15,849-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:15,941-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'pwd': '123456', 'mobilephone': 'abcd', 'regname': '小皮球'}，结果是{'status': 0, 'data': None, 'code': '20109', 'msg': '手机号码格式不正确'}
2019-03-21 22:21:16,055-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:16,065-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:16,135-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'pwd': '123456', 'mobilephone': '13412345679', 'regname': '小晚晴'}，结果是{'status': 0, 'data': None, 'code': '20110', 'msg': '手机号码已被注册'}
2019-03-21 22:21:16,236-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:16,243-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:16,309-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'pwd': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'data': None, 'code': '10001', 'msg': '登录成功'}
2019-03-21 22:21:16,409-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:16,416-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:16,491-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'pwd': '123456', 'mobilephone': '1341234567'}，结果是{'status': 0, 'data': None, 'code': '20111', 'msg': '用户名或密码错误'}
2019-03-21 22:21:16,605-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:16,612-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:16,707-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'pwd': '123456', 'mobilephone': '134123456789'}，结果是{'status': 0, 'data': None, 'code': '20111', 'msg': '用户名或密码错误'}
2019-03-21 22:21:16,808-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:16,815-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:16,877-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'status': 0, 'data': None, 'code': '20103', 'msg': '手机号不能为空'}
2019-03-21 22:21:16,978-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:16,985-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:17,078-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'status': 0, 'data': None, 'code': '20103', 'msg': '密码不能为空'}
2019-03-21 22:21:17,190-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:17,198-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:17,349-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'status': 1, 'data': {'leaveamount': '2592576.00', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430, 'type': '1', 'regtime': '2019-03-10 20:10:00.0', 'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª'}, 'code': '10001', 'msg': '充值成功'}
2019-03-21 22:21:17,357-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'sta[29 chars]t': '3209856.00', 'pwd': 'E10ADC3949BA59ABBE56[169 chars]值成功'} != {'sta[29 chars]t': '2592576.00', 'pwd': 'E10ADC3949BA59ABBE56[169 chars]值成功'}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3209856.00',
?                           - ^ ^

+           'leaveamount': '2592576.00',
?                            ^ ^ +

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '充值成功',
   'status': 1}
2019-03-21 22:21:17,473-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:17,496-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:17,566-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'status': 0, 'data': None, 'code': '20109', 'msg': '手机号码格式不正确'}
2019-03-21 22:21:17,677-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:17,690-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:17,762-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'status': 0, 'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-21 22:21:17,882-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:17,895-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:17,966-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'status': 0, 'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-21 22:21:18,072-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:18,085-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:18,152-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'mobilephone': '13512365669', 'amount': '哈哈哈'}，结果是{'status': 0, 'data': None, 'code': '20118', 'msg': '请输入数字'}
2019-03-21 22:21:18,259-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:18,272-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:18,361-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'status': 1, 'data': {'leaveamount': '2469120.00', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430, 'type': '1', 'regtime': '2019-03-10 20:10:00.0', 'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª'}, 'code': '10001', 'msg': '取现成功'}
2019-03-21 22:21:18,374-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'sta[29 chars]t': '3086400.00', 'pwd': 'E10ADC3949BA59ABBE56[169 chars]现成功'} != {'sta[29 chars]t': '2469120.00', 'pwd': 'E10ADC3949BA59ABBE56[169 chars]现成功'}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3086400.00',
?                           ^^^ ^^

+           'leaveamount': '2469120.00',
?                           ^^ ^^^

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '取现成功',
   'status': 1}
2019-03-21 22:21:18,508-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:18,524-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:18,598-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'status': 0, 'data': None, 'code': '20109', 'msg': '手机号码格式不正确'}
2019-03-21 22:21:18,713-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:18,726-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:18,798-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'status': 0, 'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-21 22:21:18,927-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:18,949-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:19,027-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'status': 0, 'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-21 22:21:19,174-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:19,196-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:19,278-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'mobilephone': '13512365669', 'amount': '100.333333'}，结果是{'status': 0, 'data': None, 'code': '20116', 'msg': '输入金额的金额小数不能超过两位'}
2019-03-21 22:21:19,486-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:19,516-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:19,608-DEBUG-loger_class.py-py14-日志信息:正在执行的第26条用例，数据是{'title': '我要变成富婆', 'loanDateType': 0, 'loanRate': 18.0, 'biddingDays': 5, 'memberId': '1123888', 'repaymemtWay': 5, 'amount': 100000, 'loanTerm': 3}，结果是{'status': 1, 'data': None, 'code': '10001', 'msg': '加标成功'}
2019-03-21 22:21:19,746-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:19,760-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:19,861-DEBUG-loger_class.py-py14-日志信息:正在执行的第None条用例，数据是{'status': 4, 'id': 'loanid'}，结果是{'status': 0, 'data': None, 'code': '20212', 'msg': '请根据数值参数的类型对应输入合法的数字'}
2019-03-21 22:21:19,880-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'status': 1, 'data': None, 'code': '10001', 'msg': '加标成功'} != {'status': 0, 'data': None, 'code': '20212', 'msg': '请根据数值参数的类型对应输入合法的数字'}
- {'code': '10001', 'data': None, 'msg': '加标成功', 'status': 1}
?            ^^^^                         ^^^^             ^

+ {'code': '20212', 'data': None, 'msg': '请根据数值参数的类型对应输入合法的数字', 'status': 0}
?           +++ ^                         ^^^^^^^^^^^^^^^^^^^             ^

2019-03-21 22:21:19,895-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 22:21:19,914-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 22:21:19,989-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'memberId': '1', 'loanId': 1, 'amount': '1000', 'password': '123456'}，结果是{'status': 0, 'data': None, 'code': '11008', 'msg': '不存在该用户'}
2019-03-21 22:21:20,108-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:00,938-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,028-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,067-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,130-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,138-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,201-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,208-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,269-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,277-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,340-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,348-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,418-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,425-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,488-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,495-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,562-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,569-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,632-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,639-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,706-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,713-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,826-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:01,843-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:01,999-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:02,007-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:02,127-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:02,136-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:02,257-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:02,264-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:02,365-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:02,376-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:02,476-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:02,485-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:02,582-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:02,591-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:02,688-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:02,695-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:02,798-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:02,807-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:02,899-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:02,906-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:02,999-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:03,006-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:03,013-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:03,021-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:03,173-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:03,190-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:03,281-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:03,292-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:03,385-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:03,396-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:03,538-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:17:03,545-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:17:03,696-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:13,265-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:13,332-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'mobilephone': '15871802615', 'pwd': '123456', 'regname': '自闭患者'}，结果是{'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'}
2019-03-21 23:18:13,339-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '10001', 'status': 1, 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ---                           --             ^

+ {'code': '20110', 'data': None, 'msg': '手机号码已被注册', 'status': 0}
?           +++                           ++++++               ^

2019-03-21 23:18:13,451-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:13,459-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:13,959-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'mobilephone': '13412345678', 'pwd': '12345', 'regname': '哎呀'}，结果是{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'}
2019-03-21 23:18:14,084-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:14,091-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:14,200-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'mobilephone': '13412345678', 'pwd': '1234567891234567891', 'regname': '妈呀'}，结果是{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'}
2019-03-21 23:18:14,317-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:14,324-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:14,385-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'mobilephone': 'abcd', 'pwd': '123456', 'regname': '小皮球'}，结果是{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
2019-03-21 23:18:14,503-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:14,509-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:14,588-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'mobilephone': '13412345679', 'pwd': '123456', 'regname': '小晚晴'}，结果是{'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'}
2019-03-21 23:18:14,707-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:14,713-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:14,789-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'mobilephone': '13512365669', 'pwd': '123456'}，结果是{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'}
2019-03-21 23:18:14,902-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:14,908-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:15,005-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'mobilephone': '1341234567', 'pwd': '123456'}，结果是{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}
2019-03-21 23:18:15,121-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:15,128-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:15,196-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'mobilephone': '134123456789', 'pwd': '123456'}，结果是{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}
2019-03-21 23:18:15,311-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:15,317-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:15,379-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'}
2019-03-21 23:18:15,488-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:15,495-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:15,563-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}
2019-03-21 23:18:15,679-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:15,685-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:15,767-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'status': 1, 'code': '10001', 'data': {'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª', 'id': 1123430, 'type': '1', 'leaveamount': '2592576.00', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'regtime': '2019-03-10 20:10:00.0'}, 'msg': '充值成功'}
2019-03-21 23:18:15,774-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'code': '10001', 'status': 1, 'data': {'mo[206 chars]值成功'} != {'status': 1, 'code': '10001', 'data': {'mo[206 chars]值成功'}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3209856.00',
?                           - ^ ^

+           'leaveamount': '2592576.00',
?                            ^ ^ +

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '充值成功',
   'status': 1}
2019-03-21 23:18:15,896-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:15,913-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:16,010-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
2019-03-21 23:18:16,130-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:16,148-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:16,219-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-21 23:18:16,369-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:16,384-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:16,459-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-21 23:18:16,577-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:16,596-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:16,667-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'mobilephone': '13512365669', 'amount': '哈哈哈'}，结果是{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'}
2019-03-21 23:18:16,789-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:16,806-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:16,897-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'status': 1, 'code': '10001', 'data': {'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª', 'id': 1123430, 'type': '1', 'leaveamount': '2469120.00', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'regtime': '2019-03-10 20:10:00.0'}, 'msg': '取现成功'}
2019-03-21 23:18:16,913-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'sta[137 chars]t': '3086400.00', 'pwd': 'E10ADC3949BA59ABBE56[61 chars]现成功'} != {'sta[137 chars]t': '2469120.00', 'pwd': 'E10ADC3949BA59ABBE56[61 chars]现成功'}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3086400.00',
?                           ^^^ ^^

+           'leaveamount': '2469120.00',
?                           ^^ ^^^

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '取现成功',
   'status': 1}
2019-03-21 23:18:17,036-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:17,052-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:17,121-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
2019-03-21 23:18:17,267-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:17,286-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:17,364-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-21 23:18:17,508-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:17,523-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:17,598-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}
2019-03-21 23:18:17,747-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:17,764-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:17,937-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'mobilephone': '13512365669', 'amount': '100.333333'}，结果是{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'}
2019-03-21 23:18:18,059-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:18,074-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:18,186-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:18,216-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:18,235-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:18,253-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:18,329-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'amount': '1000', 'password': '123456', 'loanId': 1, 'memberId': '1'}，结果是{'status': 0, 'code': '11008', 'data': None, 'msg': '不存在该用户'}
2019-03-21 23:18:18,458-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:18,474-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:18,549-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'amount': '1020', 'password': '100.333333', 'loanId': 1, 'memberId': '1'}，结果是{'status': 0, 'code': '11007', 'data': None, 'msg': '参数错误，投资金额必须是能被100整除的正整数'}
2019-03-21 23:18:18,673-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:18,690-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:18,796-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'amount': '1020', 'password': '100.333333', 'loanId': 1, 'memberId': '01010'}，结果是{'status': 0, 'code': '11007', 'data': None, 'msg': '参数错误，投资金额必须是能被100整除的正整数'}
2019-03-21 23:18:18,932-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:18,947-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:19,018-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'status': 0, 'code': '11003', 'data': None, 'msg': '参数错误:所有参数都不能为空'}
2019-03-21 23:18:19,133-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:18:19,140-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:18:19,205-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'amount': '1020', 'password': '100.333333', 'loanId': '0.2', 'memberId': '01010'}，结果是{'status': 0, 'code': '11007', 'data': None, 'msg': '参数错误，投资金额必须是能被100整除的正整数'}
2019-03-21 23:18:19,319-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:17,784-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:17,887-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'mobilephone': '15871802617', 'pwd': '123456', 'regname': '自闭患者'}，结果是{'status': 1, 'msg': '注册成功', 'data': None, 'code': '10001'}
2019-03-21 23:19:18,000-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:18,007-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:18,094-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'mobilephone': '13412345678', 'pwd': '12345', 'regname': '哎呀'}，结果是{'status': 0, 'msg': '密码长度必须为6~18', 'data': None, 'code': '20108'}
2019-03-21 23:19:18,215-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:18,222-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:18,288-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'mobilephone': '13412345678', 'pwd': '1234567891234567891', 'regname': '妈呀'}，结果是{'status': 0, 'msg': '密码长度必须为6~18', 'data': None, 'code': '20108'}
2019-03-21 23:19:18,416-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:18,423-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:18,516-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'mobilephone': 'abcd', 'pwd': '123456', 'regname': '小皮球'}，结果是{'status': 0, 'msg': '手机号码格式不正确', 'data': None, 'code': '20109'}
2019-03-21 23:19:18,658-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:18,665-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:18,734-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'mobilephone': '13412345679', 'pwd': '123456', 'regname': '小晚晴'}，结果是{'status': 0, 'msg': '手机号码已被注册', 'data': None, 'code': '20110'}
2019-03-21 23:19:18,867-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:18,874-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:18,941-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'mobilephone': '13512365669', 'pwd': '123456'}，结果是{'status': 1, 'msg': '登录成功', 'data': None, 'code': '10001'}
2019-03-21 23:19:19,055-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:19,061-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:19,127-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'mobilephone': '1341234567', 'pwd': '123456'}，结果是{'status': 0, 'msg': '用户名或密码错误', 'data': None, 'code': '20111'}
2019-03-21 23:19:19,236-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:19,243-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:19,311-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'mobilephone': '134123456789', 'pwd': '123456'}，结果是{'status': 0, 'msg': '用户名或密码错误', 'data': None, 'code': '20111'}
2019-03-21 23:19:19,442-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:19,450-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:19,515-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'status': 0, 'msg': '手机号不能为空', 'data': None, 'code': '20103'}
2019-03-21 23:19:19,627-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:19,633-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:19,727-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'status': 0, 'msg': '密码不能为空', 'data': None, 'code': '20103'}
2019-03-21 23:19:19,836-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:19,844-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:19,925-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'msg': '充值成功', 'data': {'leaveamount': '2592576.00', 'type': '1', 'regtime': '2019-03-10 20:10:00.0', 'regname': 'å°\x8få°\x8fé\x9bª', 'mobilephone': '13512365669', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430}, 'code': '10001'}
2019-03-21 23:19:19,932-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'sta[20 chars]功', 'code': '10001', 'data': {'leaveamount': '[178 chars]430}} != {'sta[20 chars]功', 'data': {'leaveamount': '2592576.00', 'typ[178 chars]001'}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3209856.00',
?                           - ^ ^

+           'leaveamount': '2592576.00',
?                            ^ ^ +

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '充值成功',
   'status': 1}
2019-03-21 23:19:20,079-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:20,100-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:20,173-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'msg': '手机号码格式不正确', 'data': None, 'code': '20109'}
2019-03-21 23:19:20,321-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:20,338-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:20,409-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117'}
2019-03-21 23:19:20,552-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:20,568-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:20,643-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117'}
2019-03-21 23:19:20,776-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:20,793-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:20,862-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'amount': '哈哈哈', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入数字', 'data': None, 'code': '20118'}
2019-03-21 23:19:20,983-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:21,000-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:21,092-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'msg': '取现成功', 'data': {'leaveamount': '2469120.00', 'type': '1', 'regtime': '2019-03-10 20:10:00.0', 'regname': 'å°\x8få°\x8fé\x9bª', 'mobilephone': '13512365669', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430}, 'code': '10001'}
2019-03-21 23:19:21,114-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'sta[44 chars]t': '3086400.00', 'type': '1', 'regtime': '201[154 chars]001'} != {'sta[44 chars]t': '2469120.00', 'type': '1', 'regtime': '201[154 chars]001'}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3086400.00',
?                           ^^^ ^^

+           'leaveamount': '2469120.00',
?                           ^^ ^^^

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '取现成功',
   'status': 1}
2019-03-21 23:19:21,234-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:21,250-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:21,320-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'msg': '手机号码格式不正确', 'data': None, 'code': '20109'}
2019-03-21 23:19:21,437-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:21,454-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:21,534-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117'}
2019-03-21 23:19:21,670-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:21,686-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:21,793-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117'}
2019-03-21 23:19:21,933-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:21,949-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:22,048-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'amount': '100.333333', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '输入金额的金额小数不能超过两位', 'data': None, 'code': '20116'}
2019-03-21 23:19:22,187-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:22,203-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:22,306-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:22,338-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:22,357-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:22,372-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:22,464-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'loanId': 1, 'amount': '1000', 'memberId': '1', 'password': '123456'}，结果是{'status': 0, 'msg': '不存在该用户', 'data': None, 'code': '11008'}
2019-03-21 23:19:22,597-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:22,613-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:22,697-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'loanId': 1, 'amount': '1020', 'memberId': '1', 'password': '100.333333'}，结果是{'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None, 'code': '11007'}
2019-03-21 23:19:22,819-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:22,837-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:22,926-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'loanId': 1, 'amount': '1020', 'memberId': '01010', 'password': '100.333333'}，结果是{'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None, 'code': '11007'}
2019-03-21 23:19:23,061-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:23,079-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:23,168-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'status': 0, 'msg': '参数错误:所有参数都不能为空', 'data': None, 'code': '11003'}
2019-03-21 23:19:23,295-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:19:23,302-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:19:23,365-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'loanId': '0.2', 'amount': '1020', 'memberId': '01010', 'password': '100.333333'}，结果是{'status': 0, 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None, 'code': '11007'}
2019-03-21 23:19:23,478-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:33,678-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:33,757-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'mobilephone': '15871802618', 'regname': '自闭患者', 'pwd': '123456'}，结果是{'data': None, 'code': '10001', 'msg': '注册成功', 'status': 1}
2019-03-21 23:20:33,877-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:33,884-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:33,976-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'mobilephone': '13412345678', 'regname': '哎呀', 'pwd': '12345'}，结果是{'data': None, 'code': '20108', 'msg': '密码长度必须为6~18', 'status': 0}
2019-03-21 23:20:34,088-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:34,097-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:34,159-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'mobilephone': '13412345678', 'regname': '妈呀', 'pwd': '1234567891234567891'}，结果是{'data': None, 'code': '20108', 'msg': '密码长度必须为6~18', 'status': 0}
2019-03-21 23:20:34,276-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:34,284-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:34,378-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'mobilephone': 'abcd', 'regname': '小皮球', 'pwd': '123456'}，结果是{'data': None, 'code': '20109', 'msg': '手机号码格式不正确', 'status': 0}
2019-03-21 23:20:34,490-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:34,498-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:34,565-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'mobilephone': '13412345679', 'regname': '小晚晴', 'pwd': '123456'}，结果是{'data': None, 'code': '20110', 'msg': '手机号码已被注册', 'status': 0}
2019-03-21 23:20:34,676-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:34,683-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:34,747-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'mobilephone': '13512365669', 'pwd': '123456'}，结果是{'data': None, 'code': '10001', 'msg': '登录成功', 'status': 1}
2019-03-21 23:20:34,855-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:34,862-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:34,930-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'mobilephone': '1341234567', 'pwd': '123456'}，结果是{'data': None, 'code': '20111', 'msg': '用户名或密码错误', 'status': 0}
2019-03-21 23:20:35,040-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:35,047-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:35,117-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'mobilephone': '134123456789', 'pwd': '123456'}，结果是{'data': None, 'code': '20111', 'msg': '用户名或密码错误', 'status': 0}
2019-03-21 23:20:35,226-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:35,233-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:35,296-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'data': None, 'code': '20103', 'msg': '手机号不能为空', 'status': 0}
2019-03-21 23:20:35,406-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:35,413-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:35,477-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'data': None, 'code': '20103', 'msg': '密码不能为空', 'status': 0}
2019-03-21 23:20:35,586-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:35,592-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:35,671-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'data': {'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430, 'leaveamount': '2592576.00', 'type': '1', 'regtime': '2019-03-10 20:10:00.0'}, 'code': '10001', 'msg': '充值成功', 'status': 1}
2019-03-21 23:20:35,678-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'data': {'id': 1123430, 'regname': 'å°\x8få°\x8fé\x[197 chars]': 1} != {'data': {'mobilephone': '13512365669', 'regname': '[197 chars]': 1}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3209856.00',
?                           - ^ ^

+           'leaveamount': '2592576.00',
?                            ^ ^ +

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '充值成功',
   'status': 1}
2019-03-21 23:20:35,802-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:35,820-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:35,900-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'data': None, 'code': '20109', 'msg': '手机号码格式不正确', 'status': 0}
2019-03-21 23:20:36,050-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:36,071-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:36,144-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'status': 0}
2019-03-21 23:20:36,325-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:36,344-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:36,417-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'status': 0}
2019-03-21 23:20:36,563-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:36,583-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:36,654-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'mobilephone': '13512365669', 'amount': '哈哈哈'}，结果是{'data': None, 'code': '20118', 'msg': '请输入数字', 'status': 0}
2019-03-21 23:20:36,797-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:36,816-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:36,915-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'mobilephone': '13512365669', 'amount': '123456'}，结果是{'data': {'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430, 'leaveamount': '2469120.00', 'type': '1', 'regtime': '2019-03-10 20:10:00.0'}, 'code': '10001', 'msg': '取现成功', 'status': 1}
2019-03-21 23:20:36,966-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'msg': '取现成功', 'code': '10001', 'data': {'[206 chars]': 1} != {'data': {'mobilephone': '13512365669', 're[206 chars]': 1}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3086400.00',
?                           ^^^ ^^

+           'leaveamount': '2469120.00',
?                           ^^ ^^^

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '取现成功',
   'status': 1}
2019-03-21 23:20:37,101-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:37,119-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:37,191-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'mobilephone': '11012345678', 'amount': '123456'}，结果是{'data': None, 'code': '20109', 'msg': '手机号码格式不正确', 'status': 0}
2019-03-21 23:20:37,310-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:37,327-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:37,401-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'mobilephone': '13512365669', 'amount': '600000'}，结果是{'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'status': 0}
2019-03-21 23:20:37,520-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:37,536-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:37,622-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'mobilephone': '13512365669', 'amount': '-1'}，结果是{'data': None, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'status': 0}
2019-03-21 23:20:37,761-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:37,777-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:37,871-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'mobilephone': '13512365669', 'amount': '100.333333'}，结果是{'data': None, 'code': '20116', 'msg': '输入金额的金额小数不能超过两位', 'status': 0}
2019-03-21 23:20:38,011-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:38,028-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:38,140-DEBUG-loger_class.py-py14-日志信息:正在执行的第26条用例，数据是{'biddingDays': 5, 'memberId': '1123888', 'loanDateType': 0, 'repaymemtWay': 5, 'amount': 100000, 'loanRate': 18.0, 'title': '借钱修别墅啦', 'loanTerm': 3}，结果是{'data': None, 'code': '10001', 'msg': '加标成功', 'status': 1}
2019-03-21 23:20:38,259-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:38,276-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:38,294-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:38,311-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:38,387-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'amount': '1000', 'password': '123456', 'memberId': '1', 'loanId': 1}，结果是{'data': None, 'code': '11008', 'msg': '不存在该用户', 'status': 0}
2019-03-21 23:20:38,511-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:38,529-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:38,636-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'amount': '1020', 'password': '100.333333', 'memberId': '1', 'loanId': 1}，结果是{'data': None, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'status': 0}
2019-03-21 23:20:38,769-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:38,786-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:38,895-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'amount': '1020', 'password': '100.333333', 'memberId': '01010', 'loanId': 1}，结果是{'data': None, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'status': 0}
2019-03-21 23:20:39,008-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:39,015-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:39,081-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'data': None, 'code': '11003', 'msg': '参数错误:所有参数都不能为空', 'status': 0}
2019-03-21 23:20:39,205-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:20:39,211-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:20:39,279-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'amount': '1020', 'password': '100.333333', 'memberId': '01010', 'loanId': '0.2'}，结果是{'data': None, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'status': 0}
2019-03-21 23:20:39,389-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:56,899-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:56,972-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'pwd': '123456', 'regname': '自闭患者', 'mobilephone': '15871802619'}，结果是{'status': 1, 'code': '10001', 'msg': '注册成功', 'data': None}
2019-03-21 23:22:57,081-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:57,087-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:57,184-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'pwd': '12345', 'regname': '哎呀', 'mobilephone': '13412345678'}，结果是{'status': 0, 'code': '20108', 'msg': '密码长度必须为6~18', 'data': None}
2019-03-21 23:22:57,292-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:57,300-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:57,389-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'pwd': '1234567891234567891', 'regname': '妈呀', 'mobilephone': '13412345678'}，结果是{'status': 0, 'code': '20108', 'msg': '密码长度必须为6~18', 'data': None}
2019-03-21 23:22:57,504-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:57,511-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:57,575-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'pwd': '123456', 'regname': '小皮球', 'mobilephone': 'abcd'}，结果是{'status': 0, 'code': '20109', 'msg': '手机号码格式不正确', 'data': None}
2019-03-21 23:22:57,684-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:57,691-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:57,763-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'pwd': '123456', 'regname': '小晚晴', 'mobilephone': '13412345679'}，结果是{'status': 0, 'code': '20110', 'msg': '手机号码已被注册', 'data': None}
2019-03-21 23:22:57,872-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:57,878-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:57,952-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'pwd': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'code': '10001', 'msg': '登录成功', 'data': None}
2019-03-21 23:22:58,060-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:58,066-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:58,153-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'pwd': '123456', 'mobilephone': '1341234567'}，结果是{'status': 0, 'code': '20111', 'msg': '用户名或密码错误', 'data': None}
2019-03-21 23:22:58,260-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:58,267-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:58,362-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'pwd': '123456', 'mobilephone': '134123456789'}，结果是{'status': 0, 'code': '20111', 'msg': '用户名或密码错误', 'data': None}
2019-03-21 23:22:58,474-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:58,483-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:58,563-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'status': 0, 'code': '20103', 'msg': '手机号不能为空', 'data': None}
2019-03-21 23:22:58,680-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:58,689-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:58,793-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'status': 0, 'code': '20103', 'msg': '密码不能为空', 'data': None}
2019-03-21 23:22:58,906-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:58,913-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:59,002-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'code': '10001', 'msg': '充值成功', 'data': {'leaveamount': '2592576.00', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'regname': 'å°\x8få°\x8fé\x9bª', 'mobilephone': '13512365669', 'id': 1123430, 'type': '1', 'regtime': '2019-03-10 20:10:00.0'}}
2019-03-21 23:22:59,027-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'sta[61 chars]t': '3209856.00', 'pwd': 'E10ADC3949BA59ABBE56[137 chars].0'}} != {'sta[61 chars]t': '2592576.00', 'pwd': 'E10ADC3949BA59ABBE56[137 chars].0'}}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3209856.00',
?                           - ^ ^

+           'leaveamount': '2592576.00',
?                            ^ ^ +

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '充值成功',
   'status': 1}
2019-03-21 23:22:59,157-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:59,178-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:59,267-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'code': '20109', 'msg': '手机号码格式不正确', 'data': None}
2019-03-21 23:22:59,391-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:59,409-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:59,480-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-21 23:22:59,630-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:59,647-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:59,718-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-21 23:22:59,839-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:22:59,857-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:22:59,942-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'amount': '哈哈哈', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20118', 'msg': '请输入数字', 'data': None}
2019-03-21 23:23:00,082-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:00,099-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:00,200-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'code': '10001', 'msg': '取现成功', 'data': {'leaveamount': '2469120.00', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'regname': 'å°\x8få°\x8fé\x9bª', 'mobilephone': '13512365669', 'id': 1123430, 'type': '1', 'regtime': '2019-03-10 20:10:00.0'}}
2019-03-21 23:23:00,219-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'status': 1, 'data': {'leaveamount': '3086400.00', 'pwd[193 chars]001'} != {'status': 1, 'code': '10001', 'msg': '取现成功', 'data': {'[193 chars].0'}}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3086400.00',
?                           ^^^ ^^

+           'leaveamount': '2469120.00',
?                           ^^ ^^^

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '取现成功',
   'status': 1}
2019-03-21 23:23:00,343-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:00,361-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:00,472-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'code': '20109', 'msg': '手机号码格式不正确', 'data': None}
2019-03-21 23:23:00,610-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:00,628-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:00,711-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-21 23:23:00,832-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:00,851-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:00,934-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-21 23:23:01,073-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:01,089-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:01,164-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'amount': '100.333333', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20116', 'msg': '输入金额的金额小数不能超过两位', 'data': None}
2019-03-21 23:23:01,293-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:01,312-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:01,392-DEBUG-loger_class.py-py14-日志信息:正在执行的第26条用例，数据是{'title': '借钱修别墅啦', 'loanDateType': 0, 'biddingDays': 5, 'amount': 100000, 'loanTerm': 3, 'repaymemtWay': 5, 'loanRate': 18.0, 'memberId': '1123888'}，结果是{'status': 1, 'code': '10001', 'msg': '加标成功', 'data': None}
2019-03-21 23:23:01,515-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:01,534-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:01,608-DEBUG-loger_class.py-py14-日志信息:正在执行的第None条用例，数据是{'id': 'loanid', 'status': 4}，结果是{'status': 0, 'code': '20212', 'msg': '请根据数值参数的类型对应输入合法的数字', 'data': None}
2019-03-21 23:23:01,629-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'status': 1, 'code': '10001', 'msg': '审核成功', 'data': None} != {'status': 0, 'code': '20212', 'msg': '请根据数值参数的类型对应输入合法的数字', 'data': None}
- {'code': '10001', 'data': None, 'msg': '审核成功', 'status': 1}
?            ^^^^                         ^^^^             ^

+ {'code': '20212', 'data': None, 'msg': '请根据数值参数的类型对应输入合法的数字', 'status': 0}
?           +++ ^                         ^^^^^^^^^^^^^^^^^^^             ^

2019-03-21 23:23:01,650-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:01,671-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:01,749-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'password': '123456', 'loanId': 1, 'amount': '1000', 'memberId': '1'}，结果是{'status': 0, 'code': '11008', 'msg': '不存在该用户', 'data': None}
2019-03-21 23:23:01,867-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:01,887-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:01,962-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'password': '100.333333', 'loanId': 1, 'amount': '1020', 'memberId': '1'}，结果是{'status': 0, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None}
2019-03-21 23:23:02,075-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:02,082-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:02,150-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'password': '100.333333', 'loanId': 1, 'amount': '1020', 'memberId': '01010'}，结果是{'status': 0, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None}
2019-03-21 23:23:02,260-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:02,266-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:02,327-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'status': 0, 'code': '11003', 'msg': '参数错误:所有参数都不能为空', 'data': None}
2019-03-21 23:23:02,437-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:23:02,444-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:23:02,514-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'password': '100.333333', 'loanId': '0.2', 'amount': '1020', 'memberId': '01010'}，结果是{'status': 0, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None}
2019-03-21 23:23:02,625-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:47,630-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:47,754-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'pwd': '123456', 'mobilephone': '15871802620', 'regname': '自闭患者'}，结果是{'status': 1, 'code': '10001', 'msg': '注册成功', 'data': None}
2019-03-21 23:28:47,865-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:47,872-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:47,943-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'pwd': '12345', 'mobilephone': '13412345678', 'regname': '哎呀'}，结果是{'status': 0, 'code': '20108', 'msg': '密码长度必须为6~18', 'data': None}
2019-03-21 23:28:48,060-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:48,067-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:48,134-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'pwd': '1234567891234567891', 'mobilephone': '13412345678', 'regname': '妈呀'}，结果是{'status': 0, 'code': '20108', 'msg': '密码长度必须为6~18', 'data': None}
2019-03-21 23:28:48,238-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:48,244-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:48,315-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'pwd': '123456', 'mobilephone': 'abcd', 'regname': '小皮球'}，结果是{'status': 0, 'code': '20109', 'msg': '手机号码格式不正确', 'data': None}
2019-03-21 23:28:48,434-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:48,442-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:48,512-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'pwd': '123456', 'mobilephone': '13412345679', 'regname': '小晚晴'}，结果是{'status': 0, 'code': '20110', 'msg': '手机号码已被注册', 'data': None}
2019-03-21 23:28:48,621-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:48,627-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:48,693-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'pwd': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'code': '10001', 'msg': '登录成功', 'data': None}
2019-03-21 23:28:48,801-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:48,808-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:48,872-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'pwd': '123456', 'mobilephone': '1341234567'}，结果是{'status': 0, 'code': '20111', 'msg': '用户名或密码错误', 'data': None}
2019-03-21 23:28:48,979-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:48,986-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:49,053-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'pwd': '123456', 'mobilephone': '134123456789'}，结果是{'status': 0, 'code': '20111', 'msg': '用户名或密码错误', 'data': None}
2019-03-21 23:28:49,170-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:49,177-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:49,236-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'status': 0, 'code': '20103', 'msg': '手机号不能为空', 'data': None}
2019-03-21 23:28:49,343-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:49,350-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:49,414-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'status': 0, 'code': '20103', 'msg': '密码不能为空', 'data': None}
2019-03-21 23:28:49,523-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:49,530-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:49,607-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'code': '10001', 'msg': '充值成功', 'data': {'regtime': '2019-03-10 20:10:00.0', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430, 'regname': 'å°\x8få°\x8fé\x9bª', 'type': '1', 'mobilephone': '13512365669', 'leaveamount': '2592576.00'}}
2019-03-21 23:28:49,614-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'sta[22 chars]1', 'data': {'regtime': '2019-03-10 20:10:00.0[176 chars]值成功'} != {'sta[22 chars]1', 'msg': '充值成功', 'data': {'regtime': '2019-0[176 chars]00'}}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3209856.00',
?                           - ^ ^

+           'leaveamount': '2592576.00',
?                            ^ ^ +

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '充值成功',
   'status': 1}
2019-03-21 23:28:49,733-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:49,755-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:49,832-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'code': '20109', 'msg': '手机号码格式不正确', 'data': None}
2019-03-21 23:28:49,956-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:49,979-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:50,057-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-21 23:28:50,182-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:50,202-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:50,280-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-21 23:28:50,432-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:50,450-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:50,523-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'amount': '哈哈哈', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20118', 'msg': '请输入数字', 'data': None}
2019-03-21 23:28:50,647-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:50,667-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:50,765-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'code': '10001', 'msg': '取现成功', 'data': {'regtime': '2019-03-10 20:10:00.0', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E', 'id': 1123430, 'regname': 'å°\x8få°\x8fé\x9bª', 'type': '1', 'mobilephone': '13512365669', 'leaveamount': '2469120.00'}}
2019-03-21 23:28:50,792-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'sta[125 chars]E', 'mobilephone': '13512365669', 'regname': '[73 chars]00'}} != {'sta[125 chars]E', 'id': 1123430, 'regname': 'å°\x8få°\x8fé\x[73 chars]00'}}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3086400.00',
?                           ^^^ ^^

+           'leaveamount': '2469120.00',
?                           ^^ ^^^

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '取现成功',
   'status': 1}
2019-03-21 23:28:50,916-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:50,935-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:51,039-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'code': '20109', 'msg': '手机号码格式不正确', 'data': None}
2019-03-21 23:28:51,159-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:51,178-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:51,283-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-21 23:28:51,406-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:51,425-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:51,500-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20117', 'msg': '请输入范围在0到50万之间的正数金额', 'data': None}
2019-03-21 23:28:51,621-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:51,641-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:51,716-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'amount': '100.333333', 'mobilephone': '13512365669'}，结果是{'status': 0, 'code': '20116', 'msg': '输入金额的金额小数不能超过两位', 'data': None}
2019-03-21 23:28:51,835-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:51,856-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:51,969-DEBUG-loger_class.py-py14-日志信息:正在执行的第26条用例，数据是{'loanDateType': 0, 'loanTerm': 3, 'amount': 100000, 'loanRate': 18.0, 'repaymemtWay': 5, 'title': '借钱修别墅啦', 'memberId': '1123888', 'biddingDays': 5}，结果是{'status': 1, 'code': '10001', 'msg': '加标成功', 'data': None}
2019-03-21 23:28:52,090-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:52,109-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:52,189-DEBUG-loger_class.py-py14-日志信息:正在执行的第None条用例，数据是{'status': 4, 'id': 'loanid'}，结果是{'status': 0, 'code': '20212', 'msg': '请根据数值参数的类型对应输入合法的数字', 'data': None}
2019-03-21 23:28:52,210-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'status': 1, 'code': '10001', 'msg': '审核成功', 'data': None} != {'status': 0, 'code': '20212', 'msg': '请根据数值参数的类型对应输入合法的数字', 'data': None}
- {'code': '10001', 'data': None, 'msg': '审核成功', 'status': 1}
?            ^^^^                         ^^^^             ^

+ {'code': '20212', 'data': None, 'msg': '请根据数值参数的类型对应输入合法的数字', 'status': 0}
?           +++ ^                         ^^^^^^^^^^^^^^^^^^^             ^

2019-03-21 23:28:52,231-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:52,252-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:52,329-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'memberId': '1', 'amount': '1000', 'password': '123456', 'loanId': 1}，结果是{'status': 0, 'code': '11008', 'msg': '不存在该用户', 'data': None}
2019-03-21 23:28:52,459-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:52,479-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:52,546-DEBUG-loger_class.py-py14-日志信息:正在执行的第22条用例，数据是{'memberId': '1', 'amount': '1020', 'password': '100.333333', 'loanId': 1}，结果是{'status': 0, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None}
2019-03-21 23:28:52,665-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:52,673-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:52,737-DEBUG-loger_class.py-py14-日志信息:正在执行的第23条用例，数据是{'memberId': '01010', 'amount': '1020', 'password': '100.333333', 'loanId': 1}，结果是{'status': 0, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None}
2019-03-21 23:28:52,851-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:52,858-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:52,920-DEBUG-loger_class.py-py14-日志信息:正在执行的第24条用例，数据是{}，结果是{'status': 0, 'code': '11003', 'msg': '参数错误:所有参数都不能为空', 'data': None}
2019-03-21 23:28:53,028-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:28:53,035-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:28:53,096-DEBUG-loger_class.py-py14-日志信息:正在执行的第25条用例，数据是{'memberId': '01010', 'amount': '1020', 'password': '100.333333', 'loanId': '0.2'}，结果是{'status': 0, 'code': '11007', 'msg': '参数错误，投资金额必须是能被100整除的正整数', 'data': None}
2019-03-21 23:28:53,205-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:08,058-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:08,137-DEBUG-loger_class.py-py14-日志信息:正在执行的第1条用例，数据是{'regname': '自闭患者', 'mobilephone': '15871802621', 'pwd': '123456'}，结果是{'status': 1, 'msg': '注册成功', 'data': None, 'code': '10001'}
2019-03-21 23:31:08,241-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:08,248-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:08,308-DEBUG-loger_class.py-py14-日志信息:正在执行的第2条用例，数据是{'regname': '哎呀', 'mobilephone': '13412345678', 'pwd': '12345'}，结果是{'status': 0, 'msg': '密码长度必须为6~18', 'data': None, 'code': '20108'}
2019-03-21 23:31:08,413-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:08,420-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:08,484-DEBUG-loger_class.py-py14-日志信息:正在执行的第3条用例，数据是{'regname': '妈呀', 'mobilephone': '13412345678', 'pwd': '1234567891234567891'}，结果是{'status': 0, 'msg': '密码长度必须为6~18', 'data': None, 'code': '20108'}
2019-03-21 23:31:08,586-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:08,594-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:08,675-DEBUG-loger_class.py-py14-日志信息:正在执行的第4条用例，数据是{'regname': '小皮球', 'mobilephone': 'abcd', 'pwd': '123456'}，结果是{'status': 0, 'msg': '手机号码格式不正确', 'data': None, 'code': '20109'}
2019-03-21 23:31:08,781-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:08,787-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:08,864-DEBUG-loger_class.py-py14-日志信息:正在执行的第5条用例，数据是{'regname': '小晚晴', 'mobilephone': '13412345679', 'pwd': '123456'}，结果是{'status': 0, 'msg': '手机号码已被注册', 'data': None, 'code': '20110'}
2019-03-21 23:31:08,981-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:08,987-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:09,053-DEBUG-loger_class.py-py14-日志信息:正在执行的第6条用例，数据是{'mobilephone': '13512365669', 'pwd': '123456'}，结果是{'status': 1, 'msg': '登录成功', 'data': None, 'code': '10001'}
2019-03-21 23:31:09,176-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:09,182-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:09,248-DEBUG-loger_class.py-py14-日志信息:正在执行的第7条用例，数据是{'mobilephone': '1341234567', 'pwd': '123456'}，结果是{'status': 0, 'msg': '用户名或密码错误', 'data': None, 'code': '20111'}
2019-03-21 23:31:09,361-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:09,368-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:09,437-DEBUG-loger_class.py-py14-日志信息:正在执行的第8条用例，数据是{'mobilephone': '134123456789', 'pwd': '123456'}，结果是{'status': 0, 'msg': '用户名或密码错误', 'data': None, 'code': '20111'}
2019-03-21 23:31:09,544-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:09,550-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:09,614-DEBUG-loger_class.py-py14-日志信息:正在执行的第9条用例，数据是{'pwd': '123456'}，结果是{'status': 0, 'msg': '手机号不能为空', 'data': None, 'code': '20103'}
2019-03-21 23:31:09,730-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:09,736-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:09,831-DEBUG-loger_class.py-py14-日志信息:正在执行的第10条用例，数据是{'mobilephone': '13412345678'}，结果是{'status': 0, 'msg': '密码不能为空', 'data': None, 'code': '20103'}
2019-03-21 23:31:09,946-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:09,953-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:10,030-DEBUG-loger_class.py-py14-日志信息:正在执行的第11条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'msg': '充值成功', 'data': {'regtime': '2019-03-10 20:10:00.0', 'leaveamount': '2592576.00', 'type': '1', 'id': 1123430, 'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E'}, 'code': '10001'}
2019-03-21 23:31:10,037-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'sta[80 chars]t': '3209856.00', 'type': '1', 'regname': 'å°\[118 chars]001'} != {'sta[80 chars]t': '2592576.00', 'type': '1', 'id': 1123430, [118 chars]001'}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3209856.00',
?                           - ^ ^

+           'leaveamount': '2592576.00',
?                            ^ ^ +

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '充值成功',
   'status': 1}
2019-03-21 23:31:10,153-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:10,178-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:10,286-DEBUG-loger_class.py-py14-日志信息:正在执行的第12条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'msg': '手机号码格式不正确', 'data': None, 'code': '20109'}
2019-03-21 23:31:10,412-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:10,432-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:10,504-DEBUG-loger_class.py-py14-日志信息:正在执行的第13条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117'}
2019-03-21 23:31:10,624-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:10,644-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:10,724-DEBUG-loger_class.py-py14-日志信息:正在执行的第14条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117'}
2019-03-21 23:31:10,844-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:10,866-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:10,951-DEBUG-loger_class.py-py14-日志信息:正在执行的第15条用例，数据是{'amount': '哈哈哈', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入数字', 'data': None, 'code': '20118'}
2019-03-21 23:31:11,102-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:11,125-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:11,217-DEBUG-loger_class.py-py14-日志信息:正在执行的第16条用例，数据是{'amount': '123456', 'mobilephone': '13512365669'}，结果是{'status': 1, 'msg': '取现成功', 'data': {'regtime': '2019-03-10 20:10:00.0', 'leaveamount': '2469120.00', 'type': '1', 'id': 1123430, 'mobilephone': '13512365669', 'regname': 'å°\x8få°\x8fé\x9bª', 'pwd': 'E10ADC3949BA59ABBE56E057F20F883E'}, 'code': '10001'}
2019-03-21 23:31:11,239-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'status': 1, 'code': '10001', 'data': {'regtime': '2019[193 chars]现成功'} != {'status': 1, 'msg': '取现成功', 'data': {'regtime': '2019-0[193 chars]001'}
  {'code': '10001',
   'data': {'id': 1123430,
-           'leaveamount': '3086400.00',
?                           ^^^ ^^

+           'leaveamount': '2469120.00',
?                           ^^ ^^^

            'mobilephone': '13512365669',
            'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
            'regname': 'å°\x8få°\x8fé\x9bª',
            'regtime': '2019-03-10 20:10:00.0',
            'type': '1'},
   'msg': '取现成功',
   'status': 1}
2019-03-21 23:31:11,358-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:11,378-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:11,458-DEBUG-loger_class.py-py14-日志信息:正在执行的第17条用例，数据是{'amount': '123456', 'mobilephone': '11012345678'}，结果是{'status': 0, 'msg': '手机号码格式不正确', 'data': None, 'code': '20109'}
2019-03-21 23:31:11,594-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:11,613-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:11,692-DEBUG-loger_class.py-py14-日志信息:正在执行的第18条用例，数据是{'amount': '600000', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117'}
2019-03-21 23:31:11,807-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:11,827-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:11,913-DEBUG-loger_class.py-py14-日志信息:正在执行的第19条用例，数据是{'amount': '-1', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '请输入范围在0到50万之间的正数金额', 'data': None, 'code': '20117'}
2019-03-21 23:31:12,032-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:12,056-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:12,137-DEBUG-loger_class.py-py14-日志信息:正在执行的第20条用例，数据是{'amount': '100.333333', 'mobilephone': '13512365669'}，结果是{'status': 0, 'msg': '输入金额的金额小数不能超过两位', 'data': None, 'code': '20116'}
2019-03-21 23:31:12,260-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:12,281-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:12,364-DEBUG-loger_class.py-py14-日志信息:正在执行的第26条用例，数据是{'loanTerm': 3, 'repaymemtWay': 5, 'memberId': '1123888', 'biddingDays': 5, 'amount': 100000, 'loanRate': 18.0, 'title': '借钱修别墅啦', 'loanDateType': 0}，结果是{'status': 1, 'msg': '加标成功', 'data': None, 'code': '10001'}
2019-03-21 23:31:12,484-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:12,505-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:12,596-DEBUG-loger_class.py-py14-日志信息:正在执行的第None条用例，数据是{'id': 'loanid', 'status': 4}，结果是{'status': 0, 'msg': '请根据数值参数的类型对应输入合法的数字', 'data': None, 'code': '20212'}
2019-03-21 23:31:12,624-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'status': 1, 'msg': '审核成功', 'data': None, 'code': '10001'} != {'status': 0, 'msg': '请根据数值参数的类型对应输入合法的数字', 'data': None, 'code': '20212'}
- {'code': '10001', 'data': None, 'msg': '审核成功', 'status': 1}
?            ^^^^                         ^^^^             ^

+ {'code': '20212', 'data': None, 'msg': '请根据数值参数的类型对应输入合法的数字', 'status': 0}
?           +++ ^                         ^^^^^^^^^^^^^^^^^^^             ^

2019-03-21 23:31:12,644-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
2019-03-21 23:31:12,665-DEBUG-loger_class.py-py14-日志信息:.....开始执行条测试用例啦.....
2019-03-21 23:31:12,743-DEBUG-loger_class.py-py14-日志信息:正在执行的第21条用例，数据是{'amount': 1000, 'memberId': '1123888', 'loanId': 1, 'password': '123456'}，结果是{'status': 0, 'msg': '不存在该标的', 'data': None, 'code': '11009'}
2019-03-21 23:31:12,765-DEBUG-loger_class.py-py14-日志信息:断言出错啦，错误是{'status': 0, 'msg': '不存在该用户', 'data': None, 'code': '11008'} != {'status': 0, 'msg': '不存在该标的', 'data': None, 'code': '11009'}
- {'code': '11008', 'data': None, 'msg': '不存在该用户', 'status': 0}
?               ^                             ^^

+ {'code': '11009', 'data': None, 'msg': '不存在该标的', 'status': 0}
?               ^                             ^^

2019-03-21 23:31:12,870-DEBUG-loger_class.py-py14-日志信息:.....用例执行完毕啦.....
